package com.example.vruttaant.ui.theme

import androidx.compose.runtime.compositionLocalOf

val LocalAppLanguage = compositionLocalOf { "en" }

object Localizations {
    val en = mapOf(
        "app_title" to "Vruttaant",
        "settings" to "Settings",
        "save" to "Save",
        "theme" to "Theme",
        "theme_system" to "System",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "search_sort" to "Search & Sort",
        "search_hint" to "Search by title, summary, source...",
        "sort_latest" to "Latest",
        "sort_relevance" to "Relevance",
        "clear" to "Clear",
        "apply" to "Apply",
        "sign_in" to "Sign In",
        "sign_in_with_google" to "Continue with Google",
        "sign_in_with_apple" to "Continue with Apple",
        "email" to "Email",
        "password" to "Password",
        "sign_in_to_bookmark" to "Sign in to bookmark stories.",
        "bookmark_missing_url" to "This story cannot be bookmarked (missing URL).",
        "bookmark_removed" to "Bookmark removed.",
        "bookmarked" to "Bookmarked.",
        "already_bookmarked" to "Already bookmarked.",
        "signed_out" to "Signed out.",
        "bookmarks" to "Bookmarks",
        "no_bookmarks" to "No bookmarks yet.",
        "feed_load_failed" to "Could not load news feed",
        "retry" to "Retry",
        "no_stories_now" to "No stories available right now.",
        "no_stories_filters" to "No stories available for the selected filters yet.",
        "all" to "All",
        "cached_feed" to "Cached feed",
        "cached_feed_with_time" to "Cached feed ({time})",
        "account" to "Account",
        "signed_in_state" to "Signed in",
        "profile_sync_hint" to "Profile and notification preferences are synced.",
        "sign_out" to "Sign Out",
        "sign_in_manage" to "Sign in to manage profile and notifications.",
        "language" to "Language",
        "category_preferences" to "Category Preferences",
        "notifications" to "Notifications",
        "notification_defaults_hint" to "Using defaults because server preferences could not be loaded.",
        "enable_notifications" to "Enable Notifications",
        "breaking_news_alerts" to "Breaking News Alerts",
        "bookmark_alerts" to "Bookmark Alerts",
        "daily_digest" to "Daily Digest",
        "registered_devices" to "Registered Devices",
        "no_notification_devices" to "No notification devices registered yet.",
        "device_removed" to "Device removed.",
        "activity_overview" to "Activity Overview",
        "recent_reading" to "Recent Reading",
        "no_recent_activity" to "No recent reading activity yet.",
        "total_views" to "Views",
        "total_bookmarks" to "Bookmarks",
        "total_translations" to "Translations",
        "total_shares" to "Shares",
        "last_active" to "Last active: {value}",
        "last_active_unknown" to "Last active: unavailable",
        "story_fallback_title" to "Story",
        "read_time_minutes" to "{minutes} min read",
        "generic_action_failed" to "Action failed. Please try again.",
        "settings_load_failed" to "Could not load profile settings right now.",
        "settings_save_failed" to "Could not save settings right now.",
        "read_more" to "Read More",
        "reader_hint" to "Swipe left from the news card to open the full article in supported mobile platforms.",
        "no_original_url" to "No original article URL available.",
        "translating" to "Translating...",
        "translated" to "Translated",
        "original" to "Original",
        "show_original" to "Show original",
        "translate" to "Translate",
        "share" to "Share",
        "translation_unavailable" to "Translation unavailable",
        "translation_unavailable_snack" to "Translation unavailable for this story. Showing original.",
        "translation_failed" to "Translation failed",
        "translation_failed_snack" to "Could not translate this story right now.",
        "add_bookmark" to "Add bookmark",
        "remove_bookmark" to "Remove bookmark",
        "tech" to "Tech",
        "politics" to "Politics",
        "sports" to "Sports",
        "business" to "Business",
        "world" to "World",
        "health" to "Health",
        "entertainment" to "Entertainment",
        "science" to "Science",
        "education" to "Education",
        "general" to "General",
        "lang_en" to "English",
        "lang_hi" to "Hindi",
        "lang_bn" to "Bengali",
        "lang_mr" to "Marathi",
        "lang_te" to "Telugu",
        "lang_ta" to "Tamil",
        "lang_gu" to "Gujarati",
        "lang_ur" to "Urdu",
        "lang_kn" to "Kannada",
        "lang_or" to "Odia",
        "lang_ml" to "Malayalam",
        "unknown_platform" to "unknown",
        "device_fallback_name" to "Device",
        "onboarding_welcome_title" to "Welcome to Vruttaant",
        "onboarding_welcome_body" to "Get short, swipeable news cards in your language. We will personalize your feed in one quick step.",
        "onboarding_continue" to "Continue",
        "onboarding_category_title" to "Choose your primary interest",
        "onboarding_category_body" to "Pick at least 3 content types to start with. You can change these anytime in settings.",
        "onboarding_start_reading" to "Start Reading",
        "onboarding_category_selection_hint" to "Select at least 3 categories ({count} selected)",
        "onboarding_reset" to "Show onboarding again"
    )

    val hi = mapOf(
        "app_title" to "वृत्तांत",
        "settings" to "सेटिंग्स",
        "save" to "सेव करें",
        "theme" to "थीम",
        "theme_system" to "सिस्टम",
        "theme_light" to "लाइट",
        "theme_dark" to "डार्क",
        "search_sort" to "खोज और क्रम",
        "search_hint" to "शीर्षक, सारांश, स्रोत से खोजें...",
        "sort_latest" to "नवीनतम",
        "sort_relevance" to "प्रासंगिक",
        "clear" to "साफ करें",
        "apply" to "लागू करें",
        "sign_in" to "साइन इन",
        "sign_in_with_google" to "Google से जारी रखें",
        "sign_in_with_apple" to "Apple से जारी रखें",
        "email" to "ईमेल",
        "password" to "पासवर्ड",
        "sign_in_to_bookmark" to "स्टोरी बुकमार्क करने के लिए साइन इन करें।",
        "bookmark_missing_url" to "यह स्टोरी बुकमार्क नहीं की जा सकती (URL नहीं मिला)।",
        "bookmark_removed" to "बुकमार्क हटा दिया गया।",
        "bookmarked" to "बुकमार्क किया गया।",
        "already_bookmarked" to "पहले से बुकमार्क है।",
        "signed_out" to "साइन आउट हो गया।",
        "bookmarks" to "बुकमार्क",
        "no_bookmarks" to "अभी कोई बुकमार्क नहीं है।",
        "feed_load_failed" to "न्यूज़ फ़ीड लोड नहीं हो सकी",
        "retry" to "फिर से प्रयास करें",
        "no_stories_now" to "अभी कोई स्टोरी उपलब्ध नहीं है।",
        "no_stories_filters" to "चुने गए फ़िल्टर के लिए कोई स्टोरी उपलब्ध नहीं है।",
        "all" to "सभी",
        "cached_feed" to "कैश किया गया फ़ीड",
        "cached_feed_with_time" to "कैश किया गया फ़ीड ({time})",
        "account" to "खाता",
        "signed_in_state" to "साइन इन है",
        "profile_sync_hint" to "प्रोफाइल और नोटिफिकेशन प्राथमिकताएँ सिंक हैं।",
        "sign_out" to "साइन आउट",
        "sign_in_manage" to "प्रोफाइल और नोटिफिकेशन प्रबंधित करने के लिए साइन इन करें।",
        "language" to "भाषा",
        "category_preferences" to "श्रेणी प्राथमिकताएँ",
        "notifications" to "नोटिफिकेशन",
        "notification_defaults_hint" to "सर्वर प्राथमिकताएँ लोड न होने के कारण डिफॉल्ट का उपयोग हो रहा है।",
        "enable_notifications" to "नोटिफिकेशन सक्षम करें",
        "breaking_news_alerts" to "ब्रेकिंग न्यूज़ अलर्ट",
        "bookmark_alerts" to "बुकमार्क अलर्ट",
        "daily_digest" to "डेली डाइजेस्ट",
        "registered_devices" to "रजिस्टर्ड डिवाइस",
        "no_notification_devices" to "अभी कोई नोटिफिकेशन डिवाइस रजिस्टर्ड नहीं है।",
        "device_removed" to "डिवाइस हटा दिया गया।",
        "activity_overview" to "गतिविधि सारांश",
        "recent_reading" to "हाल की पढ़ाई",
        "no_recent_activity" to "अभी हाल की पढ़ाई गतिविधि नहीं है।",
        "total_views" to "व्यूज़",
        "total_bookmarks" to "बुकमार्क",
        "total_translations" to "अनुवाद",
        "total_shares" to "शेयर",
        "last_active" to "आखिरी सक्रिय: {value}",
        "last_active_unknown" to "आखिरी सक्रिय: उपलब्ध नहीं",
        "story_fallback_title" to "स्टोरी",
        "read_time_minutes" to "{minutes} मिनट पढ़ें",
        "generic_action_failed" to "कार्रवाई विफल हुई। कृपया फिर से कोशिश करें।",
        "settings_load_failed" to "अभी प्रोफाइल सेटिंग्स लोड नहीं हो सकीं।",
        "settings_save_failed" to "अभी सेटिंग्स सेव नहीं हो सकीं।",
        "read_more" to "और पढ़ें",
        "reader_hint" to "समर्थित मोबाइल प्लेटफॉर्म पर पूरा लेख खोलने के लिए न्यूज़ कार्ड से बाएं स्वाइप करें।",
        "no_original_url" to "मूल लेख का URL उपलब्ध नहीं है।",
        "translating" to "अनुवाद हो रहा है...",
        "translated" to "अनूदित",
        "original" to "मूल",
        "show_original" to "मूल दिखाएँ",
        "translate" to "अनुवाद करें",
        "share" to "साझा करें",
        "translation_unavailable" to "अनुवाद उपलब्ध नहीं है",
        "translation_unavailable_snack" to "इस स्टोरी का अनुवाद उपलब्ध नहीं है। मूल दिखाया जा रहा है।",
        "translation_failed" to "अनुवाद विफल",
        "translation_failed_snack" to "अभी इस स्टोरी का अनुवाद नहीं हो सका।",
        "add_bookmark" to "बुकमार्क जोड़ें",
        "remove_bookmark" to "बुकमार्क हटाएँ",
        "tech" to "टेक",
        "politics" to "राजनीति",
        "sports" to "खेल",
        "business" to "बिजनेस",
        "world" to "विश्व",
        "health" to "स्वास्थ्य",
        "entertainment" to "मनोरंजन",
        "science" to "विज्ञान",
        "education" to "शिक्षा",
        "general" to "सामान्य",
        "lang_en" to "अंग्रेज़ी",
        "lang_hi" to "हिंदी",
        "lang_bn" to "बंगाली",
        "lang_mr" to "मराठी",
        "lang_te" to "तेलुगु",
        "lang_ta" to "तमिल",
        "lang_gu" to "गुजराती",
        "lang_ur" to "उर्दू",
        "lang_kn" to "कन्नड़",
        "lang_or" to "ओड़िया",
        "lang_ml" to "मलयालम",
        "unknown_platform" to "अअज्ञात",
        "device_fallback_name" to "डिवाइस",
        "onboarding_welcome_title" to "वृत्तांत में आपका स्वागत है",
        "onboarding_welcome_body" to "अपनी भाषा में छोटे, स्वाइप करने योग्य न्यूज़ कार्ड पढ़ें। एक छोटे चरण में हम आपका फ़ीड वैयक्तिकृत करेंगे।",
        "onboarding_continue" to "आगे बढ़ें",
        "onboarding_category_title" to "अपनी मुख्य रुचि चुनें",
        "onboarding_category_body" to "शुरुआत के लिए कम से कम 3 कंटेंट प्रकार चुनें। आप इन्हें सेटिंग्स में कभी भी बदल सकते हैं।",
        "onboarding_start_reading" to "पढ़ना शुरू करें",
        "onboarding_category_selection_hint" to "कम से कम 3 श्रेणियां चुनें ({count} चुनी गई)",
        "onboarding_reset" to "ऑनबोर्डिंग फिर से दिखाएं"
    )

    fun getString(key: String, lang: String): String {
        val map = if (lang.trim().lowercase() == "hi") hi else en
        return map[key] ?: en[key] ?: key
    }

    fun categoryLabel(category: String, lang: String): String {
        val key = category.trim().lowercase()
        return getString(key, lang)
    }

    fun languageLabel(code: String, lang: String): String {
        val key = "lang_${code.trim().lowercase()}"
        return getString(key, lang)
    }
}
